// GENERATED by tool/gen_tokens.dart from lib/app/themes/tokens/tokens.json — do not edit.
// Regenerate: dart run tool/gen_tokens.dart

import 'package:flutter/material.dart';
import 'package:flutter_starter/app/utils/constants/app_colors.dart';

import 'token_types.dart';

/// Provenance of the values below.
class DsTokenMeta {
  const DsTokenMeta._();

  static const String version = '1.0.0';
  static const String source = 'lib/app/themes/tokens/tokens.json';
}

/// Spacing scale in raw Figma px — pass through R.h()/R.w()/R.pad() at use.
class DsSpace {
  const DsSpace._();

  static const double none = 0.0;
  static const double xxs = 2.0;
  static const double xs = 4.0;
  static const double sm = 8.0;
  static const double md = 12.0;
  static const double lg = 16.0;
  static const double xl = 24.0;
  static const double xxl = 32.0;
  static const double xxxl = 48.0;

  static const Map<String, double> all = {
    'none': none,
    'xxs': xxs,
    'xs': xs,
    'sm': sm,
    'md': md,
    'lg': lg,
    'xl': xl,
    'xxl': xxl,
    'xxxl': xxxl,
  };
}

/// Corner radii in raw Figma px — wrap in R.r() at use.
class DsRadius {
  const DsRadius._();

  static const double none = 0.0;
  static const double xs = 4.0;
  static const double sm = 6.0;
  static const double md = 8.0;
  static const double lg = 12.0;
  static const double xl = 20.0;
  static const double pill = 999.0;

  static const Map<String, double> all = {
    'none': none,
    'xs': xs,
    'sm': sm,
    'md': md,
    'lg': lg,
    'xl': xl,
    'pill': pill,
  };
}

/// Stroke widths in logical px; deliberately not scaled.
class DsBorderWidth {
  const DsBorderWidth._();

  static const double hairline = 0.5;
  static const double thin = 1.0;
  static const double thick = 2.0;

  static const Map<String, double> all = {
    'hairline': hairline,
    'thin': thin,
    'thick': thick,
  };
}

/// Alpha values for state layers.
class DsOpacity {
  const DsOpacity._();

  static const double hover = 0.04;
  static const double pressed = 0.08;
  static const double disabled = 0.38;
  static const double scrim = 0.5;
  static const double muted = 0.6;

  static const Map<String, double> all = {
    'hover': hover,
    'pressed': pressed,
    'disabled': disabled,
    'scrim': scrim,
    'muted': muted,
  };
}

/// Icon box sizes in raw Figma px — wrap in R.w() at use.
class DsIconSize {
  const DsIconSize._();

  static const double sm = 16.0;
  static const double md = 20.0;
  static const double lg = 24.0;
  static const double xl = 32.0;

  static const Map<String, double> all = {
    'sm': sm,
    'md': md,
    'lg': lg,
    'xl': xl,
  };
}

/// Shadow recipes; alpha differs per theme, geometry does not.
class DsElevation {
  const DsElevation._();

  static const DsShadowToken none = DsShadowToken(
    y: 0.0,
    blur: 0.0,
    spread: 0.0,
    alphaLight: 0.0,
    alphaDark: 0.0,
  );
  static const DsShadowToken low = DsShadowToken(
    y: 1.0,
    blur: 3.0,
    spread: 0.0,
    alphaLight: 0.08,
    alphaDark: 0.32,
  );
  static const DsShadowToken medium = DsShadowToken(
    y: 4.0,
    blur: 12.0,
    spread: -2.0,
    alphaLight: 0.1,
    alphaDark: 0.4,
  );
  static const DsShadowToken high = DsShadowToken(
    y: 12.0,
    blur: 28.0,
    spread: -4.0,
    alphaLight: 0.14,
    alphaDark: 0.48,
  );

  static const Map<String, DsShadowToken> all = {
    'none': none,
    'low': low,
    'medium': medium,
    'high': high,
  };
}

/// Animation durations in milliseconds.
class DsDuration {
  const DsDuration._();

  static const Duration instant = Duration(milliseconds: 0);
  static const Duration fast = Duration(milliseconds: 120);
  static const Duration normal = Duration(milliseconds: 200);
  static const Duration slow = Duration(milliseconds: 320);
  static const Duration slower = Duration(milliseconds: 500);

  static const Map<String, Duration> all = {
    'instant': instant,
    'fast': fast,
    'normal': normal,
    'slow': slow,
    'slower': slower,
  };
}

/// Named curves, resolved to const Curves entries.
class DsCurve {
  const DsCurve._();

  static const Curve standard = Curves.easeOutCubic;
  static const Curve decelerate = Curves.decelerate;
  static const Curve emphasised = Curves.easeInOutCubicEmphasized;
  static const Curve linear = Curves.linear;

  static const Map<String, Curve> all = {
    'standard': standard,
    'decelerate': decelerate,
    'emphasised': emphasised,
    'linear': linear,
  };
}

/// Duration + curve pairs, one per interaction kind.
class DsMotion {
  const DsMotion._();

  static const DsMotionToken tap = DsMotionToken(
    duration: DsDuration.fast,
    curve: DsCurve.standard,
  );
  static const DsMotionToken reveal = DsMotionToken(
    duration: DsDuration.normal,
    curve: DsCurve.standard,
  );
  static const DsMotionToken page = DsMotionToken(
    duration: DsDuration.normal,
    curve: DsCurve.decelerate,
  );
  static const DsMotionToken sheet = DsMotionToken(
    duration: DsDuration.slow,
    curve: DsCurve.emphasised,
  );

  static const Map<String, DsMotionToken> all = {
    'tap': tap,
    'reveal': reveal,
    'page': page,
    'sheet': sheet,
  };
}

/// Semantic role -> the CustomColors method that owns the value.
/// Aliases only: the hex still lives in app_colors.dart.
class DsRole {
  const DsRole._();

  static Color surface() => CustomColors.card();
  static Color surfaceBackground() => CustomColors.artboardColor();
  static Color surfaceMuted() => CustomColors.gray();
  static Color onSurface() => CustomColors.black();
  static Color onSurfaceMuted() => CustomColors.textGrayDark();
  static Color onSurfaceSubtle() => CustomColors.textGray();
  static Color border() => CustomColors.stroke();
  static Color borderSubtle() => CustomColors.whiteStroke();
  static Color accent() => CustomColors.primary();
  static Color accentSecondary() => CustomColors.secondary();
  static Color onAccent() => CustomColors.onAccent();
  static Color danger() => CustomColors.error();
  static Color dangerSurface() => CustomColors.errorBg();
  static Color success() => CustomColors.success();
  static Color successSurface() => CustomColors.successBg();
  static Color warning() => CustomColors.warning();
  static Color warningSurface() => CustomColors.warningBg();
  static Color navSurface() => CustomColors.navbar();
  static Color navSurfaceSelected() => CustomColors.navbarSelected();

  static final Map<String, Color Function()> all = {
    'surface': surface,
    'surfaceBackground': surfaceBackground,
    'surfaceMuted': surfaceMuted,
    'onSurface': onSurface,
    'onSurfaceMuted': onSurfaceMuted,
    'onSurfaceSubtle': onSurfaceSubtle,
    'border': border,
    'borderSubtle': borderSubtle,
    'accent': accent,
    'accentSecondary': accentSecondary,
    'onAccent': onAccent,
    'danger': danger,
    'dangerSurface': dangerSurface,
    'success': success,
    'successSurface': successSurface,
    'warning': warning,
    'warningSurface': warningSurface,
    'navSurface': navSurface,
    'navSurfaceSelected': navSurfaceSelected,
  };
}

/// Roles the core palette has no method for; light/dark pairs.
class DsPalette {
  const DsPalette._();

  static const DsColorToken focusRing = DsColorToken(
    light: Color(0xFF2563EB),
    dark: Color(0xFF4B8BF5),
  );
  static const DsColorToken scrim = DsColorToken(
    light: Color(0xFF000000),
    dark: Color(0xFF000000),
  );
  static const DsColorToken surfaceSunken = DsColorToken(
    light: Color(0xFFF1F1F1),
    dark: Color(0xFF181818),
  );
  static const DsColorToken surfaceRaised = DsColorToken(
    light: Color(0xFFFFFFFF),
    dark: Color(0xFF242424),
  );
  static const DsColorToken borderStrong = DsColorToken(
    light: Color(0xFF9AA0A6),
    dark: Color(0xFF5A5A5A),
  );
  static const DsColorToken infoFg = DsColorToken(
    light: Color(0xFF3F84C4),
    dark: Color(0xFF7FB2DE),
  );
  static const DsColorToken infoBg = DsColorToken(
    light: Color(0xFFECF3F9),
    dark: Color(0xFF1A2A3A),
  );
  static const DsColorToken skeletonBase = DsColorToken(
    light: Color(0xFFECECEC),
    dark: Color(0xFF2A2A2A),
  );
  static const DsColorToken skeletonHighlight = DsColorToken(
    light: Color(0xFFF7F7F7),
    dark: Color(0xFF343434),
  );

  static const Map<String, DsColorToken> all = {
    'focusRing': focusRing,
    'scrim': scrim,
    'surfaceSunken': surfaceSunken,
    'surfaceRaised': surfaceRaised,
    'borderStrong': borderStrong,
    'infoFg': infoFg,
    'infoBg': infoBg,
    'skeletonBase': skeletonBase,
    'skeletonHighlight': skeletonHighlight,
  };
}
