// ignore_for_file: avoid_print
// Regenerates lib/app/themes/tokens/design_tokens.dart from tokens.json.
// Usage: dart run tool/gen_tokens.dart [--check] [--in <json>] [--out <dart>]
// Dependency-free: dart:io + dart:convert.

import 'dart:convert';
import 'dart:io';

const String kDefaultInput = 'lib/app/themes/tokens/tokens.json';
const String kDefaultOutput = 'lib/app/themes/tokens/design_tokens.dart';
const String kDefaultColors = 'lib/app/utils/constants/app_colors.dart';

// Only curves that exist as `static const` on Curves — a typo must fail here,
// not at compile time in the generated file.
const Map<String, String> kCurves = {
  'linear': 'Curves.linear',
  'decelerate': 'Curves.decelerate',
  'ease': 'Curves.ease',
  'easeIn': 'Curves.easeIn',
  'easeOut': 'Curves.easeOut',
  'easeInOut': 'Curves.easeInOut',
  'easeOutCubic': 'Curves.easeOutCubic',
  'easeInOutCubic': 'Curves.easeInOutCubic',
  'easeInOutCubicEmphasized': 'Curves.easeInOutCubicEmphasized',
  'fastOutSlowIn': 'Curves.fastOutSlowIn',
  'bounceOut': 'Curves.bounceOut',
  'elasticOut': 'Curves.elasticOut',
};

void main(List<String> args) {
  final flags = args.where((a) => a.startsWith('--')).toList();
  final unknown = flags
      .map((f) => f.split('=').first)
      .where(
        (f) =>
            !['--check', '--in', '--out', '--colors', '--help'].contains(f),
      );
  if (flags.contains('--help') || unknown.isNotEmpty) {
    print('''
gen_tokens - regenerate design_tokens.dart from tokens.json

  dart run tool/gen_tokens.dart            write the Dart file
  dart run tool/gen_tokens.dart --check    exit 1 if it is stale, write nothing
  --in <path>      source JSON   (default $kDefaultInput)
  --out <path>     target Dart   (default $kDefaultOutput)
  --colors <path>  CustomColors  (default $kDefaultColors)''');
    exit(unknown.isEmpty ? 0 : 64);
  }

  final input = _option(args, '--in') ?? kDefaultInput;
  final output = _option(args, '--out') ?? kDefaultOutput;
  final colors = _option(args, '--colors') ?? kDefaultColors;

  final jsonFile = File(input);
  if (!jsonFile.existsSync()) _fail('No token file at $input');

  final Map<String, dynamic> tokens =
      jsonDecode(jsonFile.readAsStringSync()) as Map<String, dynamic>;
  final generated = generateTokens(
    tokens,
    source: input,
    customColors: customColorMethods(File(colors)),
  );

  final dartFile = File(output);
  if (args.contains('--check')) {
    final current = dartFile.existsSync() ? dartFile.readAsStringSync() : '';
    if (current == generated) {
      print('design_tokens.dart is up to date with $input');
      return;
    }
    _fail('$output is stale. Run: dart run tool/gen_tokens.dart');
  }

  dartFile.parent.createSync(recursive: true);
  dartFile.writeAsStringSync(generated);
  print('Wrote $output from $input '
      '(${_groupCount(tokens)} token groups)');
}

/// Every `static Color name()` CustomColors declares. Empty means "skip the
/// check" — an alias typo then only surfaces when the generated file compiles.
Set<String> customColorMethods(File file) {
  if (!file.existsSync()) {
    stderr.writeln('WARNING: ${file.path} not found — colorAlias unchecked.');
    return const {};
  }
  return RegExp(r'static\s+Color\s+(\w+)\s*\(\s*\)')
      .allMatches(file.readAsStringSync())
      .map((m) => m.group(1)!)
      .toSet();
}

/// The whole generator: token map in, Dart source out. Pure, so a test can
/// call it and compare against the committed file.
String generateTokens(
  Map<String, dynamic> tokens, {
  String source = kDefaultInput,
  Set<String> customColors = const {},
}) {
  final b = StringBuffer();
  final version = (tokens['version'] ?? '0').toString();

  b.writeln('// GENERATED by tool/gen_tokens.dart from $source — do not edit.');
  b.writeln('// Regenerate: dart run tool/gen_tokens.dart');
  b.writeln();
  b.writeln("import 'package:flutter/material.dart';");
  b.writeln("import 'package:flutter_starter/app/utils/constants/app_colors.dart';");
  b.writeln();
  b.writeln("import 'token_types.dart';");
  b.writeln();
  b.writeln('/// Provenance of the values below.');
  b.writeln('class DsTokenMeta {');
  b.writeln('  const DsTokenMeta._();');
  b.writeln();
  b.writeln("  static const String version = '$version';");
  b.writeln("  static const String source = '$source';");
  b.writeln('}');

  _numberClass(b, tokens, 'spacing', 'DsSpace',
      'Spacing scale in raw Figma px — pass through R.h()/R.w()/R.pad() at use.');
  _numberClass(b, tokens, 'radius', 'DsRadius',
      'Corner radii in raw Figma px — wrap in R.r() at use.');
  _numberClass(b, tokens, 'border', 'DsBorderWidth',
      'Stroke widths in logical px; deliberately not scaled.');
  _numberClass(b, tokens, 'opacity', 'DsOpacity', 'Alpha values for state layers.');
  _numberClass(b, tokens, 'iconSize', 'DsIconSize',
      'Icon box sizes in raw Figma px — wrap in R.w() at use.');

  _elevationClass(b, tokens);
  _durationClass(b, tokens);
  _curveClass(b, tokens);
  _motionClass(b, tokens);
  _aliasClass(b, tokens, customColors);
  _paletteClass(b, tokens);

  return b.toString();
}

// ---------- emitters ----------

void _numberClass(
  StringBuffer b,
  Map<String, dynamic> tokens,
  String key,
  String className,
  String doc,
) {
  final group = _group(tokens, key);
  if (group.isEmpty) return;
  b.writeln();
  b.writeln('/// $doc');
  b.writeln('class $className {');
  b.writeln('  const $className._();');
  b.writeln();
  group.forEach((name, value) {
    b.writeln('  static const double ${_id(name)} = ${_num(value, key, name)};');
  });
  b.writeln();
  b.writeln('  static const Map<String, double> all = {');
  group.forEach((name, _) => b.writeln("    '$name': ${_id(name)},"));
  b.writeln('  };');
  b.writeln('}');
}

void _elevationClass(StringBuffer b, Map<String, dynamic> tokens) {
  final group = _group(tokens, 'elevation');
  if (group.isEmpty) return;
  b.writeln();
  b.writeln('/// Shadow recipes; alpha differs per theme, geometry does not.');
  b.writeln('class DsElevation {');
  b.writeln('  const DsElevation._();');
  b.writeln();
  group.forEach((name, raw) {
    final m = _asMap(raw, 'elevation.$name');
    b.writeln('  static const DsShadowToken ${_id(name)} = DsShadowToken(');
    b.writeln('    y: ${_num(m['y'], 'elevation.$name', 'y')},');
    b.writeln('    blur: ${_num(m['blur'], 'elevation.$name', 'blur')},');
    b.writeln('    spread: ${_num(m['spread'], 'elevation.$name', 'spread')},');
    b.writeln('    alphaLight: ${_num(m['alphaLight'], 'elevation.$name', 'alphaLight')},');
    b.writeln('    alphaDark: ${_num(m['alphaDark'], 'elevation.$name', 'alphaDark')},');
    b.writeln('  );');
  });
  b.writeln();
  b.writeln('  static const Map<String, DsShadowToken> all = {');
  group.forEach((name, _) => b.writeln("    '$name': ${_id(name)},"));
  b.writeln('  };');
  b.writeln('}');
}

void _durationClass(StringBuffer b, Map<String, dynamic> tokens) {
  final group = _group(tokens, 'duration');
  if (group.isEmpty) return;
  b.writeln();
  b.writeln('/// Animation durations in milliseconds.');
  b.writeln('class DsDuration {');
  b.writeln('  const DsDuration._();');
  b.writeln();
  group.forEach((name, value) {
    final ms = _num(value, 'duration', name);
    b.writeln('  static const Duration ${_id(name)} = '
        'Duration(milliseconds: ${ms.split('.').first});');
  });
  b.writeln();
  b.writeln('  static const Map<String, Duration> all = {');
  group.forEach((name, _) => b.writeln("    '$name': ${_id(name)},"));
  b.writeln('  };');
  b.writeln('}');
}

void _curveClass(StringBuffer b, Map<String, dynamic> tokens) {
  final group = _group(tokens, 'curve');
  if (group.isEmpty) return;
  b.writeln();
  b.writeln('/// Named curves, resolved to const Curves entries.');
  b.writeln('class DsCurve {');
  b.writeln('  const DsCurve._();');
  b.writeln();
  group.forEach((name, value) {
    final curve = kCurves[value.toString()];
    if (curve == null) {
      _fail('curve.$name: "$value" is not a known const Curves entry.\n'
          'Allowed: ${kCurves.keys.join(', ')}');
    }
    b.writeln('  static const Curve ${_id(name)} = $curve;');
  });
  b.writeln();
  b.writeln('  static const Map<String, Curve> all = {');
  group.forEach((name, _) => b.writeln("    '$name': ${_id(name)},"));
  b.writeln('  };');
  b.writeln('}');
}

void _motionClass(StringBuffer b, Map<String, dynamic> tokens) {
  final group = _group(tokens, 'motion');
  if (group.isEmpty) return;
  final durations = _group(tokens, 'duration');
  final curves = _group(tokens, 'curve');
  b.writeln();
  b.writeln('/// Duration + curve pairs, one per interaction kind.');
  b.writeln('class DsMotion {');
  b.writeln('  const DsMotion._();');
  b.writeln();
  group.forEach((name, raw) {
    final m = _asMap(raw, 'motion.$name');
    final d = m['duration'].toString();
    final c = m['curve'].toString();
    if (!durations.containsKey(d)) _fail('motion.$name: unknown duration "$d"');
    if (!curves.containsKey(c)) _fail('motion.$name: unknown curve "$c"');
    b.writeln('  static const DsMotionToken ${_id(name)} = DsMotionToken(');
    b.writeln('    duration: DsDuration.${_id(d)},');
    b.writeln('    curve: DsCurve.${_id(c)},');
    b.writeln('  );');
  });
  b.writeln();
  b.writeln('  static const Map<String, DsMotionToken> all = {');
  group.forEach((name, _) => b.writeln("    '$name': ${_id(name)},"));
  b.writeln('  };');
  b.writeln('}');
}

void _aliasClass(
  StringBuffer b,
  Map<String, dynamic> tokens,
  Set<String> customColors,
) {
  final group = _group(tokens, 'colorAlias');
  if (group.isEmpty) return;
  b.writeln();
  b.writeln('/// Semantic role -> the CustomColors method that owns the value.');
  b.writeln('/// Aliases only: the hex still lives in app_colors.dart.');
  b.writeln('class DsRole {');
  b.writeln('  const DsRole._();');
  b.writeln();
  group.forEach((name, target) {
    if (customColors.isNotEmpty && !customColors.contains('$target')) {
      _fail('colorAlias.$name: CustomColors has no $target() method.\n'
          'Add it to app_colors.dart, or declare the role under "colorRole" '
          'with an explicit light/dark hex pair.');
    }
    b.writeln('  static Color ${_id(name)}() => CustomColors.$target();');
  });
  b.writeln();
  b.writeln('  static final Map<String, Color Function()> all = {');
  group.forEach((name, _) => b.writeln("    '$name': ${_id(name)},"));
  b.writeln('  };');
  b.writeln('}');
}

void _paletteClass(StringBuffer b, Map<String, dynamic> tokens) {
  final group = _group(tokens, 'colorRole');
  if (group.isEmpty) return;
  b.writeln();
  b.writeln('/// Roles the core palette has no method for; light/dark pairs.');
  b.writeln('class DsPalette {');
  b.writeln('  const DsPalette._();');
  b.writeln();
  group.forEach((name, raw) {
    final m = _asMap(raw, 'colorRole.$name');
    b.writeln('  static const DsColorToken ${_id(name)} = DsColorToken(');
    b.writeln('    light: ${_hex(m['light'], 'colorRole.$name.light')},');
    b.writeln('    dark: ${_hex(m['dark'], 'colorRole.$name.dark')},');
    b.writeln('  );');
  });
  b.writeln();
  b.writeln('  static const Map<String, DsColorToken> all = {');
  group.forEach((name, _) => b.writeln("    '$name': ${_id(name)},"));
  b.writeln('  };');
  b.writeln('}');
}

// ---------- helpers ----------

String? _option(List<String> args, String name) {
  for (var i = 0; i < args.length; i++) {
    if (args[i] == name && i + 1 < args.length) return args[i + 1];
    if (args[i].startsWith('$name=')) return args[i].substring(name.length + 1);
  }
  return null;
}

Map<String, dynamic> _group(Map<String, dynamic> tokens, String key) {
  final value = tokens[key];
  if (value == null) return const {};
  return _asMap(value, key);
}

Map<String, dynamic> _asMap(Object? value, String where) {
  if (value is Map<String, dynamic>) return value;
  _fail('$where must be a JSON object, got ${value.runtimeType}');
}

int _groupCount(Map<String, dynamic> tokens) =>
    tokens.entries.where((e) => e.value is Map).length;

/// Dart doubles always carry a decimal point so the emitted literal is typed.
String _num(Object? value, String group, String name) {
  if (value is! num) _fail('$group.$name must be a number, got "$value"');
  return value is int ? '$value.0' : value.toString();
}

/// "#RRGGBB" or "#AARRGGBB" -> a const Color literal.
String _hex(Object? value, String where) {
  final raw = value?.toString().replaceAll('#', '').toUpperCase() ?? '';
  if (raw.length != 6 && raw.length != 8) {
    _fail('$where must be #RRGGBB or #AARRGGBB, got "$value"');
  }
  if (!RegExp(r'^[0-9A-F]+$').hasMatch(raw)) _fail('$where is not hex: "$value"');
  return 'Color(0x${raw.length == 6 ? 'FF$raw' : raw})';
}

/// Token names come from a design tool, so reject anything not a Dart id.
String _id(String name) {
  if (!RegExp(r'^[a-z][A-Za-z0-9]*$').hasMatch(name)) {
    _fail('Token name "$name" is not lowerCamelCase — rename it in tokens.json');
  }
  return name;
}

Never _fail(String message) {
  stderr.writeln('ERROR: $message');
  exit(1);
}
