/// Flutter icons OwnIcon
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OwnIcon
///      fonts:
///       - asset: fonts/OwnIcon.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class OwnIcon {
  OwnIcon._();

  static const _kFontFam = 'OwnIcon';
  static const String? _kFontPkg = null;

  static const IconData bicycle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData private_car = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bike = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scooter = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_mark = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData driving_licence = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chash = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData online_walet = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData documents = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
