import 'package:get/get_navigation/src/root/internacionalization.dart';

class TextConst extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          //Common
          'common_continue': 'Continue',
          'common_skip': 'Skip',
          'common_back': 'Back',
          'common_done': 'Done',
          'common_cancel': 'Cancel',
          'common_submit': 'Submit',
          'common_yes': 'Yes',
          'common_no': 'No',
          'common_loading': 'Loading',
          'common_error': 'Error',
          'common_success': 'Success',
          'common_warning': 'Warning',
          'common_alert': 'Alert',
          'common_confirm': 'Confirm',
          'common_choose': 'Choose',
          'common_select': 'Select',
          'common_search': 'Search',
          'common_filter': 'Filter',
          'common_sort': 'Sort',
          'common_reset': 'Reset',
          'common_clear': 'Clear',
          'common_next': 'Next',
          'common_phone': 'Phone',
          'common_email': 'Email',
          'common_or': 'OR',

          //Onboarding
          'onboarding_title_1': 'Welcome to\nYaad 💖',
          'onboarding_title_2': 'Connecting faith',
          'onboarding_title_3': 'Business & Community',
          'onboarding_subtitle_1':
              'Building stronger communities through faith and compassion together.',
          'onboarding_subtitle_2':
              'Stay connected with your faith community wherever you are, anytime, and keep growing together in unity',
          'onboarding_subtitle_3':
              'Join a community of believers making a positive difference locally and globally through faith driven actions',
          'onboarding_get_started': 'Get Started',

          //auth screen
          'signin_welcome': 'Welcome to Yaad',
          'signin_subtitle': 'Please enter your registered email & password',
          'email_address': 'Email Address',
          'enter_email_address': 'Enter email address',
          'password': 'Password',
          'enter_password': 'Enter password',
          'forgot_password?': 'Forgot Password?',
          'forgot_password': 'Forgot Password',
          'signin': 'Sign In',
          'logic': 'Login',
          'or': 'or',
          'login_with_google': 'Login with Google',
          'dont_have_account': 'Don’t have an account?',
          'create_new_account': 'Create New Account',
          'sent_otp_subtitle':
              'Enter the email address associated with your account.',
          'email_or_phone': 'Email or Phone number',
          'enter_email_or_phone': 'Enter email or phone number',
          'verification': 'Verification',
          'verify_sub_text': 'We’ve the code send to your email-',
          'otp': 'OTP',
          'didnt_resend_code': 'Didnt receive code?',
          'resend_code': 'Resend Code',
          'please_wait': 'Please wait',
          'wait_for_timer_complete':
              'You can resend code after the timer completes',
          'resend_code_success': 'Resend code success',
          'set_up_new_password': 'Set-Up New Password',
          'set_up_new_password_subtitle':
              'Create a new password to secure your account and continue using Yaad',
          'new_password': 'New Password',
          'confirm_password': 'Confirm Password',
          'reset_password': 'Reset Password',
          'first_name': 'First Name',
          'enter_first_name': 'Enter First Name',
          'last_name': 'Last Name',
          'enter_last_name': 'Enter Last Name',
          'phone_optional': 'Phone (Optional)',
          'enter_phone_number': 'Enter phone Number',
          'enter_confirm_password': 'Enter confirm password',
          'address': 'Address',
          'enter_address': 'Enter address',
          'i_agree_to_yaad': 'I Agree to Yaad',
          'terms': 'Terms',
          'privacy_policy': 'Privacy Policy.',
          'create_account': 'Create Account',
          'accept_terms': 'Accept Terms & Conditions',
          'please_accept_terms': 'Please accept terms & conditions',
          'create_account_with_google': 'Create Account with Google',
          'already_have_an_account': 'Already have an account?',
          'language': 'Language',
          'log_in': 'Log In',

          // Report & Block
          'report': 'Report',
          'report_post': 'Report Post',
          'report_comment': 'Report Comment',
          'report_user': 'Report User',
          'report_event': 'Report Event',
          'report_product': 'Report Product',
          'report_service': 'Report Service',
          'report_message': 'Report Message',
          'why_are_you_reporting': 'Why are you reporting this?',
          'describe_issue': 'Please describe the issue...',
          'submit_report': 'Submit Report',
          'report_submitted':
              'Thank you for your report. We will review it within 24 hours.',
          'report_failed': 'Failed to submit report. Please try again.',
          'please_select_reason': 'Please select a reason for reporting.',
          'block': 'Block',
          'block_user': 'Block User',
          'block_user_confirm': 'Are you sure you want to block',
          'block_user_description':
              'They won\'t be able to see your posts or contact you. You can unblock them anytime from settings.',
          'user_blocked': 'User has been blocked successfully.',
          'block_failed': 'Failed to block user. Please try again.',
          'unblock': 'Unblock',
          'unblock_user': 'Unblock User',
          'user_unblocked': 'User has been unblocked.',
          'blocked_users': 'Blocked Users',
          'no_blocked_users': 'You haven\'t blocked anyone yet.',
          'error': 'Error',
          'success': 'Success',
          'cancel': 'Cancel',
        },
        'bn_BD': {
          //Common
          'common_continue': 'চালিয়ে যান',
          'common_skip': 'এড়িয়ে যান',
          'common_back': 'পিছনে',
          'common_done': 'সম্পন্ন',
          'common_cancel': 'বাতিল',
          'common_submit': 'জমা দিন',
          'common_yes': 'হ্যাঁ',
          'common_no': 'না',
          'common_loading': 'লোড হচ্ছে',
          'common_error': 'ত্রুটি',
          'common_success': 'সাফল্য',
          'common_warning': 'সতর্কতা',
          'common_alert': 'সতর্কবার্তা',
          'common_confirm': 'নিশ্চিত করুন',
          'common_choose': 'নির্বাচন করুন',
          'common_select': 'বেছে নিন',
          'common_search': 'অনুসন্ধান করুন',
          'common_filter': 'ছাঁকনি',
          'common_sort': 'সাজান',
          'common_reset': 'রিসেট',
          'common_clear': 'মুছে ফেলুন',
          'common_next': 'পরবর্তী',

          // Onboarding
          'onboarding_title_1': 'অ্যাডভেন্টসার্কেলে\nস্বাগতম 💖',
          'onboarding_title_2': 'বিশ্বাসের সাথে সংযুক্ত',
          'onboarding_title_3': 'ব্যবসা ও সম্প্রদায়',
          'onboarding_subtitle_1':
              'বিশ্বাস ও সহানুভূতির মাধ্যমে একসাথে শক্তিশালী সম্প্রদায় গড়ে তোলা।',
          'onboarding_subtitle_2':
              'আপনার বিশ্বাসের সম্প্রদায়ের সাথে সংযুক্ত থাকুন যেকোনো সময়, যেকোনো জায়গা থেকে এবং ঐক্যের সাথে এগিয়ে চলুন।',
          'onboarding_subtitle_3':
              'বিশ্বাসভিত্তিক কাজের মাধ্যমে স্থানীয় এবং বৈশ্বিক পর্যায়ে ইতিবাচক পরিবর্তন আনতে একত্রিত হন।',
          'onboarding_get_started': 'শুরু করুন',

          //Auth screen
          'signin_welcome': 'অ্যাডভেন্টসার্কেলে স্বাগতম',
          'signin_subtitle': 'আপনার নিবন্ধিত ইমেইল ও পাসওয়ার্ড লিখুন',
          'email_address': 'ইমেইল ঠিকানা',
          'enter_email_address': 'ইমেইল ঠিকানা লিখুন',
          'password': 'পাসওয়ার্ড',
          'enter_password': 'পাসওয়ার্ড লিখুন',
          'forgot_password?': 'পাসওয়ার্ড ভুলে গেছেন?',
          'forgot_password': 'পাসওয়ার্ড ভুলে গেছেন',
          'signin': 'সাইন ইন',
          'or': 'অথবা',
          'signin_with_google': 'গুগল দিয়ে সাইন ইন করুন',
          'dont_have_account': 'কোনো অ্যাকাউন্ট নেই?',
          'create_new_account': 'নতুন অ্যাকাউন্ট তৈরি করুন',
          'sent_otp_subtitle':
              'আপনার অ্যাকাউন্টের সাথে যুক্ত ইমেইল বা ফোন নম্বর লিখুন।',
          'email_or_phone': 'ইমেইল অথবা ফোন নম্বর',
          'enter_email_or_phone': 'ইমেইল অথবা ফোন নম্বর লিখুন',
          'verification': 'যাচাইকরণ',
          'verify_sub_text': 'আমরা কোড পাঠিয়েছি আপনার ইমেইলে -',
          'otp': 'ওটিপি',
          'didnt_resend_code': 'কোড পাননি?',
          'resend_code': 'পুনরায় কোড পাঠান',
          'please_wait': 'অনুগ্রহ করে অপেক্ষা করুন',
          'wait_for_timer_complete': 'টাইমার শেষ হলে কোড পুনরায় পাঠাতে পারবেন',
          'resend_code_success': 'কোড সফলভাবে পুনরায় পাঠানো হয়েছে',
          'set_up_new_password': 'নতুন পাসওয়ার্ড সেট করুন',
          'set_up_new_password_subtitle':
              'আপনার অ্যাকাউন্ট নিরাপদ রাখতে নতুন পাসওয়ার্ড তৈরি করুন এবং অ্যাডভেন্টসার্কেল ব্যবহার চালিয়ে যান',
          'new_password': 'নতুন পাসওয়ার্ড',
          'confirm_password': 'পাসওয়ার্ড নিশ্চিত করুন',
          'reset_password': 'পাসওয়ার্ড রিসেট করুন',
          'first_name': 'প্রথম নাম',
          'enter_first_name': 'প্রথম নাম লিখুন',
          'last_name': 'শেষ নাম',
          'enter_last_name': 'শেষ নাম লিখুন',
          'phone_optional': 'ফোন (ঐচ্ছিক)',
          'enter_phone_number': 'ফোন নম্বর লিখুন',
          'enter_confirm_password': 'পাসওয়ার্ড আবার লিখুন',
          'address': 'ঠিকানা',
          'enter_address': 'ঠিকানা লিখুন',
          'i_agree_to_yaad': 'আমি অ্যাডভেন্টসার্কেলের সাথে একমত',
          'terms': 'শর্তাবলী',
          'privacy_policy': 'গোপনীয়তা নীতি',
          'create_account': 'অ্যাকাউন্ট তৈরি করুন',
          'accept_terms': 'শর্তাবলী গ্রহণ করুন',
          'please_accept_terms': 'অনুগ্রহ করে শর্তাবলী গ্রহণ করুন',
          'create_account_with_google': 'গুগল দিয়ে অ্যাকাউন্ট তৈরি করুন',
          'already_have_an_account': 'আগেই কি একটি অ্যাকাউন্ট আছে?',
          'language': 'ভাষা',
          'log_in': 'লগ ইন',

          // Report & Block
          'report': 'রিপোর্ট',
          'report_post': 'পোস্ট রিপোর্ট করুন',
          'report_comment': 'মন্তব্য রিপোর্ট করুন',
          'report_user': 'ব্যবহারকারী রিপোর্ট করুন',
          'report_event': 'ইভেন্ট রিপোর্ট করুন',
          'report_product': 'পণ্য রিপোর্ট করুন',
          'report_service': 'সেবা রিপোর্ট করুন',
          'report_message': 'বার্তা রিপোর্ট করুন',
          'why_are_you_reporting': 'আপনি কেন এটি রিপোর্ট করছেন?',
          'describe_issue': 'অনুগ্রহ করে সমস্যাটি বর্ণনা করুন...',
          'submit_report': 'রিপোর্ট জমা দিন',
          'report_submitted':
              'আপনার রিপোর্টের জন্য ধন্যবাদ। আমরা ২৪ ঘণ্টার মধ্যে এটি পর্যালোচনা করব।',
          'report_failed':
              'রিপোর্ট জমা দিতে ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।',
          'please_select_reason':
              'অনুগ্রহ করে রিপোর্ট করার কারণ নির্বাচন করুন।',
          'block': 'ব্লক',
          'block_user': 'ব্যবহারকারী ব্লক করুন',
          'block_user_confirm': 'আপনি কি নিশ্চিত যে আপনি ব্লক করতে চান',
          'block_user_description':
              'তারা আপনার পোস্ট দেখতে বা আপনার সাথে যোগাযোগ করতে পারবে না। আপনি সেটিংস থেকে যেকোনো সময় তাদের আনব্লক করতে পারবেন।',
          'user_blocked': 'ব্যবহারকারী সফলভাবে ব্লক করা হয়েছে।',
          'block_failed':
              'ব্যবহারকারী ব্লক করতে ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।',
          'unblock': 'আনব্লক',
          'unblock_user': 'ব্যবহারকারী আনব্লক করুন',
          'user_unblocked': 'ব্যবহারকারী আনব্লক করা হয়েছে।',
          'blocked_users': 'ব্লক করা ব্যবহারকারীরা',
          'no_blocked_users': 'আপনি এখনও কাউকে ব্লক করেননি।',
          'error': 'ত্রুটি',
          'success': 'সাফল্য',
          'cancel': 'বাতিল',
        },
      };
}
